language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

compiler: 
  - gcc
  - clang

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost-all-dev

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" ;fi                             ;fi

script:
  - mkdir build && cd build && cmake .. && cmake --build . --target install

